### ISSUE TITLE
custom Storage

### ISSUE THREAD

**Issue by Tenchu98** [MCreator-Examples/Projects#60]
### Feature overview

An overview of how to accomplish common storage options in the latest mcreator version.

### Feature checklist

1. How to add double chest style blocks like the rustic cabinet.
2. How to add multiblock storage like the magneticraft chelves.
3. How to create a storage network like Arcane Archives.

### Files and Sources

https://media.forgecdn.net/attachments/202/776/2017-04-23_09.png
https://www.curseforge.com/minecraft/mc-mods/magneticraft
https://www.curseforge.com/minecraft/mc-mods/arcane-archives

### BEFORE YOU POST! Please do the following.

- [X] I have looked if the feature as been requested already on the issue tab and could not find a similar issue.
- [X] I have have searched NorthWestTrees Gaming's MCreator Playlists and could not find the feature I want
- [X] I understand that not all things are possible and that the tutorial may not be made any time soon or at all

**Comment by northwesttreesgaming** [comment]
Currently, this is only possible using GUIs you can open GUIs at different coordinates so if you want to make double blocks then this would require you to pass the open GUI location to a dedicated block eg. the bottom locker, that has an inventory.
Simply just use Y - 1 if the block location is below the right-click even and open that location for the GUI.

Otherwise, it's not possible to get to advanced storage without third-party plugins or custom code.
